version: "3.2"
services:
  mpc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4567:4567"
    volumes:
      - type: bind
        source: ./
        target: /mpc

    entrypoint:
      - tail
      - -f
      - /var/log/bootstrap.log
volumes:
  .: